# install.ps1 — cc-switch one-click installer
# Sets up: model switching functions, OAuth bypass, slash command
# Run: .\install.ps1
# Web: irm https://raw.githubusercontent.com/luyuehm/cc-switch/main/install.ps1 | iex

param(
    [switch]$Force,
    [switch]$DryRun,
    [switch]$NoProfile,
    [switch]$NoSwitchMd
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host ""
Write-Host "=== cc-switch Installer ===" -ForegroundColor Cyan
Write-Host "  Installs model switching + OAuth login bypass" -ForegroundColor Gray
Write-Host ""

# === [1/4] Copy cc-switch.ps1 to ~/.claude/ ===
Write-Host "[1/4] Installing cc-switch.ps1..." -ForegroundColor Yellow
$ccSwitchSrc = Join-Path $scriptDir "cc-switch.ps1"
$ccSwitchDst = "$env:USERPROFILE\.claude\cc-switch.ps1"

if (Test-Path $ccSwitchSrc) {
    if (-not $DryRun) {
        Copy-Item $ccSwitchSrc $ccSwitchDst -Force
        Write-Host "  Copied to $ccSwitchDst" -ForegroundColor Green
    }
} else {
    Write-Host "  ERROR: cc-switch.ps1 not found at $ccSwitchSrc" -ForegroundColor Red
    exit 1
}

# === [2/4] Setup cc-switch.env (secrets, NOT committed to git) ===
Write-Host "[2/4] Setting up cc-switch.env..." -ForegroundColor Yellow
$envExample = Join-Path $scriptDir ".env.example"
$envTarget = "$env:USERPROFILE\.claude\cc-switch.env"

if (Test-Path $envTarget) {
    Write-Host "  Already exists: $envTarget" -ForegroundColor Gray
} elseif (Test-Path $envExample) {
    if (-not $DryRun) {
        Copy-Item $envExample $envTarget
        Write-Host "  Created $envTarget (from .env.example)" -ForegroundColor Green
        Write-Host ""
        Write-Host "  >>> EDIT THIS FILE NOW with your credentials: <<<" -ForegroundColor Yellow
        Write-Host "      notepad $envTarget" -ForegroundColor White
        Write-Host ""
    }
} else {
    # If running via irm | iex (no local .env.example), create from scratch
    if (-not $DryRun) {
        @"
# cc-switch secrets — NEVER commit this file
ANTHROPIC_API_KEY=your-api-key-here
ANTHROPIC_BASE_URL=https://your-proxy.example.com
CPA_MODELS_URL=https://your-proxy.example.com/v1/models
"@ | Set-Content $envTarget -Encoding UTF8
        Write-Host "  Created $envTarget (fill in your credentials)" -ForegroundColor Green
        Write-Host ""
        Write-Host "  >>> EDIT THIS FILE NOW: <<<" -ForegroundColor Yellow
        Write-Host "      notepad $envTarget" -ForegroundColor White
        Write-Host ""
    }
}

# === [3/4] Inject into pwsh $PROFILE ===
if (-not $NoProfile) {
    Write-Host "[3/4] Updating PowerShell profile..." -ForegroundColor Yellow

    $profilePath = $PROFILE
    $profileDir = Split-Path $profilePath -Parent
    if (-not (Test-Path $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }

    $marker = "# >>> cc-switch (auto-generated by install.ps1)"
    $endMarker = "# <<< cc-switch"

    $profileBlock = @"

$marker
# cc-switch — model switching + OAuth bypass
# https://github.com/luyuehm/cc-switch
if (Test-Path "$env:USERPROFILE\.claude\cc-switch.ps1") {
    . "$env:USERPROFILE\.claude\cc-switch.ps1"
} else {
    Write-Host "[cc-switch] Not installed. Clone: git clone https://github.com/luyuehm/cc-switch.git; cd cc-switch; .\install.ps1" -ForegroundColor Yellow
}
$endMarker
"@

    if (Test-Path $profilePath) {
        $existing = Get-Content $profilePath -Raw
        if ($existing -match [regex]::Escape($marker)) {
            if ($Force) {
                # Remove old block, append new one
                $cleaned = $existing -replace "(?s)$marker.*?$endMarker", ""
                $cleaned + "`r`n$profileBlock" | Set-Content $profilePath -Encoding UTF8
                Write-Host "  Replaced existing cc-switch block." -ForegroundColor Green
            } else {
                Write-Host "  Profile already has cc-switch block. Use -Force to overwrite." -ForegroundColor Gray
            }
        } else {
            if (-not $DryRun) {
                Add-Content $profilePath "`r`n$profileBlock"
                Write-Host "  Appended to $profilePath" -ForegroundColor Green
            }
        }
    } else {
        if (-not $DryRun) {
            $profileBlock | Set-Content $profilePath -Encoding UTF8
            Write-Host "  Created $profilePath" -ForegroundColor Green
        }
    }
}

# === [4/4] Copy switch.md to Claude Code commands ===
if (-not $NoSwitchMd) {
    Write-Host "[4/4] Installing /switch slash command..." -ForegroundColor Yellow
    $switchMdSrc = Join-Path $scriptDir "switch.md"
    $switchMdDst = "$env:USERPROFILE\.claude\commands\switch.md"

    if (Test-Path $switchMdSrc) {
        if (-not $DryRun) {
            $cmdDir = Split-Path $switchMdDst -Parent
            if (-not (Test-Path $cmdDir)) {
                New-Item -ItemType Directory -Path $cmdDir -Force | Out-Null
            }
            Copy-Item $switchMdSrc $switchMdDst -Force
            Write-Host "  Copied to $switchMdDst" -ForegroundColor Green
        }
    } else {
        Write-Host "  switch.md not found, skipping." -ForegroundColor Gray
    }
}

Write-Host ""
Write-Host "=== Installation Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit your .env file:" -ForegroundColor White
Write-Host "     notepad `$env:USERPROFILE\.claude\cc-switch.env" -ForegroundColor Gray
Write-Host ""
Write-Host "  2. Reload profile:" -ForegroundColor White
Write-Host "     . `$PROFILE" -ForegroundColor Gray
Write-Host ""
Write-Host "  3. Try it:" -ForegroundColor White
Write-Host "     cc                # show menu" -ForegroundColor Gray
Write-Host "     cc gpt-5.5        # switch model + launch Claude Code" -ForegroundColor Gray
Write-Host "     cc-status         # model inventory" -ForegroundColor Gray
Write-Host ""
